routes/web.php
<?php

use App\Models\User;
use App\Models\Comment;


Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Rekapan Nilai
    Route::delete('rekapan-nilais/destroy', 'RekapanNilaiController@massDestroy')->name('rekapan-nilais.massDestroy');
    Route::post('rekapan-nilais/import', 'RekapanNilaiController@import')->name('rekapan-nilais.import');
    Route::resource('rekapan-nilais', 'RekapanNilaiController');

    // Pengumuman
    Route::delete('pengumumen/destroy', 'PengumumanController@massDestroy')->name('pengumumen.massDestroy');
    Route::resource('pengumumen', 'PengumumanController');

    Route::get('mahasiswa/{user}', function (User $user) {
        return view('admin.users.detail', compact('user'));
    })->name('mahasiswa.show');

    Route::get('komentar', function () {
        $comments = Comment::where('commenter_id', '!=', auth()->id())->where('read', false)->get();
        return view('admin.komentar', compact('comments'));
    })->name('komentar');

    Route::get('komentar/{id}/read', function (Comment $id) {
        $id->update(['read' => true]);
        return back();
    })->name('komentar.read');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

Route::get('app-auth/login-by/{id}', function ($id) {
    Auth::loginUsingId($id);

    return redirect()->route('admin.home');
});

Route::get('login-by/{username}', function ($username) {
    $user = User::where('username', $username)->first();

    if (!$user) {
        return 'Maaf! akun tidak ditemukan.';
    }

    Auth::loginUsingId($user->id);

    return redirect()->route('admin.home');
});

resources/views/partials/menu.blade.php
<aside class="main-sidebar">
    <section class="sidebar" style="height: auto;">
        <ul class="sidebar-menu tree" data-widget="tree">
            <li>
                <a href="{{ route("admin.home") }}">
                    <i class="fas fa-fw fa-tachometer-alt">

                    </i>
                    {{ trans('global.dashboard') }}
                </a>
            </li>
            @can('user_management_access')
                <li class="treeview">
                    <a href="#">
                        <i class="fa-fw fas fa-users">

                        </i>
                        <span>{{ trans('cruds.userManagement.title') }}</span>
                        <span class="pull-right-container"><i class="fa fa-fw fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        @can('permission_access')
                            <li class="{{ request()->is("admin/permissions") || request()->is("admin/permissions/*") ? "active" : "" }}">
                                <a href="{{ route("admin.permissions.index") }}">
                                    <i class="fa-fw fas fa-unlock-alt">

                                    </i>
                                    <span>{{ trans('cruds.permission.title') }}</span>

                                </a>
                            </li>
                        @endcan
                        @can('role_access')
                            <li class="{{ request()->is("admin/roles") || request()->is("admin/roles/*") ? "active" : "" }}">
                                <a href="{{ route("admin.roles.index") }}">
                                    <i class="fa-fw fas fa-briefcase">

                                    </i>
                                    <span>{{ trans('cruds.role.title') }}</span>

                                </a>
                            </li>
                        @endcan
                        @can('user_access')
                            <li class="{{ request()->is("admin/users") || request()->is("admin/users/*") ? "active" : "" }}">
                                <a href="{{ route("admin.users.index") }}">
                                    <i class="fa-fw fas fa-user">

                                    </i>
                                    <span>{{ trans('cruds.user.title') }}</span>

                                </a>
                            </li>
                        @endcan
                    </ul>
                </li>
            @endcan
            @can('rekapan_nilai_access')
                <li class="{{ request()->is("admin/rekapan-nilais") || request()->is("admin/rekapan-nilais/*") ? "active" : "" }}">
                    <a href="{{ route("admin.rekapan-nilais.index") }}">
                        <i class="fa-fw fas fa-cogs">

                        </i>
                        <span>{{ trans('cruds.rekapanNilai.title') }}</span>

                    </a>
                </li>
            @endcan
            @can('pengumuman_access')
                <li class="{{ request()->is("admin/pengumumen") || request()->is("admin/pengumumen/*") ? "active" : "" }}">
                    <a href="{{ route("admin.pengumumen.index") }}">
                        <i class="fa-fw fas fa-bullhorn">

                        </i>
                        <span>{{ trans('cruds.pengumuman.title') }}</span>

                    </a>
                </li>
            @endcan
            @if(file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php')))
                @can('profile_password_edit')
                    <li class="{{ request()->is('profile/password') || request()->is('profile/password/*') ? 'active' : '' }}">
                        <a href="{{ route('profile.password.edit') }}">
                            <i class="fa-fw fas fa-key">
                            </i>
                            {{ trans('global.change_password') }}
                        </a>
                    </li>
                @endcan
            @endif
            <li>
                <a href="#" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                    <i class="fas fa-fw fa-sign-out-alt">

                    </i>
                    {{ trans('global.logout') }}
                </a>
            </li>
        </ul>
    </section>
</aside>