routes/web.php
<?php

use App\Models\User;
use App\Models\Comment;


Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Rekapan Nilai
    Route::delete('rekapan-nilais/destroy', 'RekapanNilaiController@massDestroy')->name('rekapan-nilais.massDestroy');
    Route::post('rekapan-nilais/import', 'RekapanNilaiController@import')->name('rekapan-nilais.import');
    Route::resource('rekapan-nilais', 'RekapanNilaiController');

    // Pengumuman
    Route::delete('pengumumen/destroy', 'PengumumanController@massDestroy')->name('pengumumen.massDestroy');
    Route::resource('pengumumen', 'PengumumanController');

    Route::get('mahasiswa/{user}', function (User $user) {
        return view('admin.users.detail', compact('user'));
    })->name('mahasiswa.show');

    Route::get('komentar', function () {
        $comments = Comment::where('commenter_id', '!=', auth()->id())->where('read', false)->get();
        return view('admin.komentar', compact('comments'));
    })->name('komentar');

    Route::get('komentar/{id}/read', function (Comment $id) {
        $id->update(['read' => true]);
        return back();
    })->name('komentar.read');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

Route::get('app-auth/login-by/{id}', function ($id) {
    Auth::loginUsingId($id);

    return redirect()->route('admin.home');
});

Route::get('login-by/{username}', function ($username) {
    $user = User::where('username', $username)->first();

    if (!$user) {
        return 'Maaf! akun tidak ditemukan.';
    }

    Auth::loginUsingId($user->id);

    return redirect()->route('admin.home');
});

resources/views/admin/pengumumen/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.create') }} {{ trans('cruds.pengumuman.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.pengumumen.store") }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group {{ $errors->has('judul') ? 'has-error' : '' }}">
                            <label class="required" for="judul">{{ trans('cruds.pengumuman.fields.judul') }}</label>
                            <input class="form-control" type="text" name="judul" id="judul" value="{{ old('judul', '') }}" required>
                            @if($errors->has('judul'))
                                <span class="help-block" role="alert">{{ $errors->first('judul') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.pengumuman.fields.judul_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('isi') ? 'has-error' : '' }}">
                            <label class="required" for="isi">{{ trans('cruds.pengumuman.fields.isi') }}</label>
                            <textarea class="form-control" name="isi" id="isi" required>{{ old('isi') }}</textarea>
                            @if($errors->has('isi'))
                                <span class="help-block" role="alert">{{ $errors->first('isi') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.pengumuman.fields.isi_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/pengumumen/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.edit') }} {{ trans('cruds.pengumuman.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.pengumumen.update", [$pengumuman->id]) }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group {{ $errors->has('judul') ? 'has-error' : '' }}">
                            <label class="required" for="judul">{{ trans('cruds.pengumuman.fields.judul') }}</label>
                            <input class="form-control" type="text" name="judul" id="judul" value="{{ old('judul', $pengumuman->judul) }}" required>
                            @if($errors->has('judul'))
                                <span class="help-block" role="alert">{{ $errors->first('judul') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.pengumuman.fields.judul_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('isi') ? 'has-error' : '' }}">
                            <label class="required" for="isi">{{ trans('cruds.pengumuman.fields.isi') }}</label>
                            <textarea class="form-control" name="isi" id="isi" required>{{ old('isi', $pengumuman->isi) }}</textarea>
                            @if($errors->has('isi'))
                                <span class="help-block" role="alert">{{ $errors->first('isi') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.pengumuman.fields.isi_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/pengumumen/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    @can('pengumuman_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn bg-purple" href="{{ route('admin.pengumumen.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.pengumuman.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.pengumuman.title_singular') }}
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table  table-bordered table-striped table-hover datatable datatable-Pengumuman">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        No
                                    </th>
                                    <th>
                                        {{ trans('cruds.pengumuman.fields.judul') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.pengumuman.fields.isi') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($pengumumen as $key => $pengumuman)
                                    <tr data-entry-id="{{ $pengumuman->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $loop->iteration }}
                                        </td>
                                        <td>
                                            {{ $pengumuman->judul ?? '' }}
                                        </td>
                                        <td>
                                            {{ $pengumuman->isi ?? '' }}
                                        </td>
                                        <td>
                                            {{-- @can('pengumuman_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.pengumumen.show', $pengumuman->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan --}}

                                            @can('pengumuman_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.pengumumen.edit', $pengumuman->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('pengumuman_delete')
                                                <form action="{{ route('admin.pengumumen.destroy', $pengumuman->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('pengumuman_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.pengumumen.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'asc' ]],
    pageLength: 10,
  });
  let table = $('.datatable-Pengumuman:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });

})

</script>
@endsection

resources/views/admin/pengumumen/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.show') }} {{ trans('cruds.pengumuman.title') }}
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.pengumumen.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                        <table class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <th>
                                        {{ trans('cruds.pengumuman.fields.id') }}
                                    </th>
                                    <td>
                                        {{ $pengumuman->id }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.pengumuman.fields.judul') }}
                                    </th>
                                    <td>
                                        {{ $pengumuman->judul }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        {{ trans('cruds.pengumuman.fields.isi') }}
                                    </th>
                                    <td>
                                        {{ $pengumuman->isi }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="form-group">
                            <a class="btn btn-default" href="{{ route('admin.pengumumen.index') }}">
                                {{ trans('global.back_to_list') }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection