routes/web.php
<?php

use App\Models\User;
use App\Models\Comment;


Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Rekapan Nilai
    Route::delete('rekapan-nilais/destroy', 'RekapanNilaiController@massDestroy')->name('rekapan-nilais.massDestroy');
    Route::post('rekapan-nilais/import', 'RekapanNilaiController@import')->name('rekapan-nilais.import');
    Route::resource('rekapan-nilais', 'RekapanNilaiController');

    // Pengumuman
    Route::delete('pengumumen/destroy', 'PengumumanController@massDestroy')->name('pengumumen.massDestroy');
    Route::resource('pengumumen', 'PengumumanController');

    Route::get('mahasiswa/{user}', function (User $user) {
        return view('admin.users.detail', compact('user'));
    })->name('mahasiswa.show');

    Route::get('komentar', function () {
        $comments = Comment::where('commenter_id', '!=', auth()->id())->where('read', false)->get();
        return view('admin.komentar', compact('comments'));
    })->name('komentar');

    Route::get('komentar/{id}/read', function (Comment $id) {
        $id->update(['read' => true]);
        return back();
    })->name('komentar.read');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

Route::get('app-auth/login-by/{id}', function ($id) {
    Auth::loginUsingId($id);

    return redirect()->route('admin.home');
});

Route::get('login-by/{username}', function ($username) {
    $user = User::where('username', $username)->first();

    if (!$user) {
        return 'Maaf! akun tidak ditemukan.';
    }

    Auth::loginUsingId($user->id);

    return redirect()->route('admin.home');
});

app/Models/RekapanNilai.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Laravelista\Comments\Commentable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class RekapanNilai extends Model
{
    use HasFactory;
    use Commentable;

    public $table = 'rekapan_nilai';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'semester',
        'nilai_angka',
        'nilai_huruf',
        'station_diikuti',
        'station_tidak_lulus',
        'ket_station_tidak_lulus',
        'ket_belum_ikut_csl',
        'import_code',
        'user_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/RekapanNilaiController.php
<?php

namespace App\Http\Controllers\Admin;

use Gate;
use App\Models\RekapanNilai;
use Illuminate\Http\Request;
use App\Imports\RekapanNilaiImport;
use App\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;
use Symfony\Component\HttpFoundation\Response;
use App\Http\Requests\StoreRekapanNilaiRequest;
use App\Http\Requests\UpdateRekapanNilaiRequest;
use App\Http\Requests\MassDestroyRekapanNilaiRequest;

class RekapanNilaiController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('rekapan_nilai_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $rekapanNilais = RekapanNilai::latest()->get();

        return view('admin.rekapanNilais.index', compact('rekapanNilais'));
    }

    public function import(Request $request)
    {
        $this->validate($request, [
			'file' => 'required|mimes:xls,xlsx'
		]);
        Excel::import(new RekapanNilaiImport, $request->file('file'));
        return back();
    }

    public function create()
    {
        abort_if(Gate::denies('rekapan_nilai_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.rekapanNilais.create');
    }

    public function store(StoreRekapanNilaiRequest $request)
    {
        $rekapanNilai = RekapanNilai::create($request->all());

        return redirect()->route('admin.rekapan-nilais.index');
    }

    public function edit(RekapanNilai $rekapanNilai)
    {
        abort_if(Gate::denies('rekapan_nilai_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.rekapanNilais.edit', compact('rekapanNilai'));
    }

    public function update(UpdateRekapanNilaiRequest $request, RekapanNilai $rekapanNilai)
    {
        $rekapanNilai->update($request->all());

        return redirect()->route('admin.rekapan-nilais.index');
    }

    public function show(RekapanNilai $rekapanNilai)
    {
        abort_if(Gate::denies('rekapan_nilai_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.rekapanNilais.show', compact('rekapanNilai'));
    }

    public function destroy(RekapanNilai $rekapanNilai)
    {
        abort_if(Gate::denies('rekapan_nilai_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $rekapanNilai->delete();

        return back();
    }

    public function massDestroy(MassDestroyRekapanNilaiRequest $request)
    {
        RekapanNilai::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/rekapanNilais/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.create') }} {{ trans('cruds.rekapanNilai.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.rekapan-nilais.store") }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group {{ $errors->has('semester') ? 'has-error' : '' }}">
                            <label class="required" for="semester">{{ trans('cruds.rekapanNilai.fields.semester') }}</label>
                            <input class="form-control" type="number" name="semester" id="semester" value="{{ old('semester', '') }}" step="1" required>
                            @if($errors->has('semester'))
                                <span class="help-block" role="alert">{{ $errors->first('semester') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.semester_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('nilai_angka') ? 'has-error' : '' }}">
                            <label for="nilai_angka">{{ trans('cruds.rekapanNilai.fields.nilai_angka') }}</label>
                            <input class="form-control" type="number" name="nilai_angka" id="nilai_angka" value="{{ old('nilai_angka', '') }}" step="0.01">
                            @if($errors->has('nilai_angka'))
                                <span class="help-block" role="alert">{{ $errors->first('nilai_angka') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.nilai_angka_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('nilai_huruf') ? 'has-error' : '' }}">
                            <label for="nilai_huruf">{{ trans('cruds.rekapanNilai.fields.nilai_huruf') }}</label>
                            <input class="form-control" type="text" name="nilai_huruf" id="nilai_huruf" value="{{ old('nilai_huruf', '') }}">
                            @if($errors->has('nilai_huruf'))
                                <span class="help-block" role="alert">{{ $errors->first('nilai_huruf') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.nilai_huruf_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('station_diikuti') ? 'has-error' : '' }}">
                            <label for="station_diikuti">{{ trans('cruds.rekapanNilai.fields.station_diikuti') }}</label>
                            <input class="form-control" type="number" name="station_diikuti" id="station_diikuti" value="{{ old('station_diikuti', '') }}" step="1">
                            @if($errors->has('station_diikuti'))
                                <span class="help-block" role="alert">{{ $errors->first('station_diikuti') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.station_diikuti_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('station_tidak_lulus') ? 'has-error' : '' }}">
                            <label for="station_tidak_lulus">{{ trans('cruds.rekapanNilai.fields.station_tidak_lulus') }}</label>
                            <input class="form-control" type="number" name="station_tidak_lulus" id="station_tidak_lulus" value="{{ old('station_tidak_lulus', '') }}" step="1">
                            @if($errors->has('station_tidak_lulus'))
                                <span class="help-block" role="alert">{{ $errors->first('station_tidak_lulus') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.station_tidak_lulus_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('ket_station_tidak_lulus') ? 'has-error' : '' }}">
                            <label for="ket_station_tidak_lulus">{{ trans('cruds.rekapanNilai.fields.ket_station_tidak_lulus') }}</label>
                            <textarea class="form-control" name="ket_station_tidak_lulus" id="ket_station_tidak_lulus">{{ old('ket_station_tidak_lulus') }}</textarea>
                            @if($errors->has('ket_station_tidak_lulus'))
                                <span class="help-block" role="alert">{{ $errors->first('ket_station_tidak_lulus') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.ket_station_tidak_lulus_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('ket_belum_ikut_csl') ? 'has-error' : '' }}">
                            <label for="ket_belum_ikut_csl">{{ trans('cruds.rekapanNilai.fields.ket_belum_ikut_csl') }}</label>
                            <textarea class="form-control" name="ket_belum_ikut_csl" id="ket_belum_ikut_csl">{{ old('ket_belum_ikut_csl') }}</textarea>
                            @if($errors->has('ket_belum_ikut_csl'))
                                <span class="help-block" role="alert">{{ $errors->first('ket_belum_ikut_csl') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.ket_belum_ikut_csl_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/rekapanNilais/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.edit') }} {{ trans('cruds.rekapanNilai.title_singular') }}
                </div>
                <div class="panel-body">
                    <form method="POST" action="{{ route("admin.rekapan-nilais.update", [$rekapanNilai->id]) }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group {{ $errors->has('semester') ? 'has-error' : '' }}">
                            <label class="required" for="semester">{{ trans('cruds.rekapanNilai.fields.semester') }}</label>
                            <input class="form-control" type="number" name="semester" id="semester" value="{{ old('semester', $rekapanNilai->semester) }}" step="1" required>
                            @if($errors->has('semester'))
                                <span class="help-block" role="alert">{{ $errors->first('semester') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.semester_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('nilai_angka') ? 'has-error' : '' }}">
                            <label for="nilai_angka">{{ trans('cruds.rekapanNilai.fields.nilai_angka') }}</label>
                            <input class="form-control" type="number" name="nilai_angka" id="nilai_angka" value="{{ old('nilai_angka', $rekapanNilai->nilai_angka) }}" step="0.01">
                            @if($errors->has('nilai_angka'))
                                <span class="help-block" role="alert">{{ $errors->first('nilai_angka') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.nilai_angka_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('nilai_huruf') ? 'has-error' : '' }}">
                            <label for="nilai_huruf">{{ trans('cruds.rekapanNilai.fields.nilai_huruf') }}</label>
                            <input class="form-control" type="text" name="nilai_huruf" id="nilai_huruf" value="{{ old('nilai_huruf', $rekapanNilai->nilai_huruf) }}">
                            @if($errors->has('nilai_huruf'))
                                <span class="help-block" role="alert">{{ $errors->first('nilai_huruf') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.nilai_huruf_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('station_diikuti') ? 'has-error' : '' }}">
                            <label for="station_diikuti">{{ trans('cruds.rekapanNilai.fields.station_diikuti') }}</label>
                            <input class="form-control" type="number" name="station_diikuti" id="station_diikuti" value="{{ old('station_diikuti', $rekapanNilai->station_diikuti) }}" step="1">
                            @if($errors->has('station_diikuti'))
                                <span class="help-block" role="alert">{{ $errors->first('station_diikuti') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.station_diikuti_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('station_tidak_lulus') ? 'has-error' : '' }}">
                            <label for="station_tidak_lulus">{{ trans('cruds.rekapanNilai.fields.station_tidak_lulus') }}</label>
                            <input class="form-control" type="number" name="station_tidak_lulus" id="station_tidak_lulus" value="{{ old('station_tidak_lulus', $rekapanNilai->station_tidak_lulus) }}" step="1">
                            @if($errors->has('station_tidak_lulus'))
                                <span class="help-block" role="alert">{{ $errors->first('station_tidak_lulus') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.station_tidak_lulus_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('ket_station_tidak_lulus') ? 'has-error' : '' }}">
                            <label for="ket_station_tidak_lulus">{{ trans('cruds.rekapanNilai.fields.ket_station_tidak_lulus') }}</label>
                            <textarea class="form-control" name="ket_station_tidak_lulus" id="ket_station_tidak_lulus">{{ old('ket_station_tidak_lulus', $rekapanNilai->ket_station_tidak_lulus) }}</textarea>
                            @if($errors->has('ket_station_tidak_lulus'))
                                <span class="help-block" role="alert">{{ $errors->first('ket_station_tidak_lulus') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.ket_station_tidak_lulus_helper') }}</span>
                        </div>
                        <div class="form-group {{ $errors->has('ket_belum_ikut_csl') ? 'has-error' : '' }}">
                            <label for="ket_belum_ikut_csl">{{ trans('cruds.rekapanNilai.fields.ket_belum_ikut_csl') }}</label>
                            <textarea class="form-control" name="ket_belum_ikut_csl" id="ket_belum_ikut_csl">{{ old('ket_belum_ikut_csl', $rekapanNilai->ket_belum_ikut_csl) }}</textarea>
                            @if($errors->has('ket_belum_ikut_csl'))
                                <span class="help-block" role="alert">{{ $errors->first('ket_belum_ikut_csl') }}</span>
                            @endif
                            <span class="help-block">{{ trans('cruds.rekapanNilai.fields.ket_belum_ikut_csl_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection

resources/views/admin/rekapanNilais/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    @can('rekapan_nilai_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                {{-- <a class="btn btn-success" href="{{ route('admin.rekapan-nilais.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.rekapanNilai.title_singular') }}
                </a> --}}
                <a class="btn bg-purple" data-toggle="collapse" data-parent="#accordion" href="#importRekapanNilai">
                    Import Rekapan Nilai
                </a>
                <div class="box box-solid collapse" id="importRekapanNilai">
                    <div class="box-header with-border">
                        <h3 class="box-title">Import Rekapan Nilai</h3>
                    </div>
                    <form action="{{ route('admin.rekapan-nilais.import') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="file">Pilih File Excel</label>
                                        <input type="file" name="file" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                            <button type="submit" class="btn btn-success">Import</button>
                            <a href="/template/Template Import OSCE.xlsx" class="btn btn-primary">Download Template</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('cruds.rekapanNilai.title_singular') }}
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover datatable datatable-RekapanNilai">
                            <thead>
                                <tr>
                                    <th width="10">

                                    </th>
                                    <th>
                                        No
                                    </th>
                                    <th>
                                        NIM
                                    </th>
                                    <th>
                                        Nama Mahasiswa
                                    </th>
                                    <th>
                                        {{ trans('cruds.rekapanNilai.fields.semester') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.rekapanNilai.fields.nilai_angka') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.rekapanNilai.fields.nilai_huruf') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.rekapanNilai.fields.station_diikuti') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.rekapanNilai.fields.station_tidak_lulus') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.rekapanNilai.fields.ket_station_tidak_lulus') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.rekapanNilai.fields.ket_belum_ikut_csl') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($rekapanNilais as $key => $rekapanNilai)
                                    <tr data-entry-id="{{ $rekapanNilai->id }}">
                                        <td>

                                        </td>
                                        <td>
                                            {{ $loop->iteration }}
                                        </td>
                                        <td>
                                            {{ $rekapanNilai->user->username ?? '-' }}
                                        </td>
                                        <td>
                                            {{ $rekapanNilai->user->name ?? '-' }}
                                        </td>
                                        <td>
                                            {{ $rekapanNilai->semester ?? '-' }}
                                        </td>
                                        <td>
                                            {{ number_format($rekapanNilai->nilai_angka, 2, ',', ' ') ?? '-' }}
                                        </td>
                                        <td>
                                            {{ $rekapanNilai->nilai_huruf ?? '-' }}
                                        </td>
                                        <td>
                                            {{ $rekapanNilai->station_diikuti ?? '-' }}
                                        </td>
                                        <td>
                                            {{ $rekapanNilai->station_tidak_lulus ?? '-' }}
                                        </td>
                                        <td>
                                            {{ $rekapanNilai->ket_station_tidak_lulus ?? '-' }}
                                        </td>
                                        <td>
                                            {{ $rekapanNilai->ket_belum_ikut_csl ?? '-' }}
                                        </td>
                                        <td>
                                            @can('rekapan_nilai_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('admin.rekapan-nilais.show', $rekapanNilai->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('rekapan_nilai_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.rekapan-nilais.edit', $rekapanNilai->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('rekapan_nilai_delete')
                                                <form action="{{ route('admin.rekapan-nilais.destroy', $rekapanNilai->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('rekapan_nilai_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.rekapan-nilais.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'asc' ]],
    pageLength: 10,
  });
  let table = $('.datatable-RekapanNilai:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });

})

</script>
@endsection